exclude: >
    (?x)(
        ^tests/_snaps/|
        ^tests/testthat/_snaps/|
        ^tests/testthat/testdata/
    )
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: trailing-whitespace
  - id: check-yaml
    args: [--allow-multiple-documents]
  - id: detect-aws-credentials
    args: [--allow-missing-credentials]
  - id: detect-private-key
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.41.0
  hooks:
  - id: markdownlint
    args: [ --fix, --disable=MD007, --disable=MD013, --disable=MD024, --disable=MD033, --disable=MD041 ]
- repo: https://github.com/codespell-project/codespell
  rev: v2.3.0
  hooks:
  - id: codespell
-   repo: https://github.com/lorenzwalthert/precommit
    rev: v0.1.2
    hooks:
    - id: lintr
      verbose: true
      args: [--warn_only]



